# Generated by Django 4.0.1 on 2022-01-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'cart', 'verbose_name_plural': 'carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cartItem', 'verbose_name_plural': 'cartItems'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='foodItems',
        ),
    ]
