# Generated by Django 4.0.1 on 2022-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catg_Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catg_name', models.CharField(max_length=100)),
                ('catg_desc', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
