# Generated by Django 4.0.1 on 2022-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catg_foods',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='catg_foods',
            name='catg_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='catg_foods',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
