# Generated by Django 4.0.1 on 2022-01-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0002_alter_catg_foods_options_alter_catg_foods_catg_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('food_desc', models.TextField()),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_pic', models.ImageField(height_field=200, upload_to='the_uploaded_images', width_field=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverFood.catg_foods')),
            ],
        ),
    ]
