# Generated by Django 4.0.1 on 2022-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0004_alter_food_items_options_alter_food_items_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='food_price',
            field=models.IntegerField(),
        ),
    ]
