# Generated by Django 4.0.1 on 2022-01-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0006_alter_food_items_food_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='food_pic',
            field=models.ImageField(upload_to='the_uploaded_images'),
        ),
        migrations.AlterField(
            model_name='food_items',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
