# Generated by Django 4.0.1 on 2022-01-19 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0007_alter_food_items_food_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
