# Generated by Django 4.0.1 on 2022-01-20 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0008_food_items_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
