# Generated by Django 3.2.9 on 2022-01-31 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0010_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
