# Generated by Django 4.0.1 on 2022-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0011_alter_contact_us_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_names', models.CharField(max_length=100, unique=True)),
                ('food_pics', models.ImageField(upload_to='the_uploaded_images')),
                ('food_identify', models.CharField(max_length=100)),
            ],
        ),
    ]
