# Generated by Django 3.2.12 on 2022-03-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0012_food_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='date',
        ),
    ]
