# Generated by Django 3.2.12 on 2022-03-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverFood', '0013_remove_contact_us_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='deliverFood.Author')),
            ],
        ),
    ]
